<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="9.1.2" />
    <PackageReference Include="Microsoft.Orleans.Runtime" Version="9.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicrosoftOrleans.Application\MicrosoftOrleans.Application.csproj" />
    <ProjectReference Include="..\MicrosoftOrleans.Domain\MicrosoftOrleans.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Migrations\" />
  </ItemGroup>

</Project>
